id = "edi"
name = "EDI"
version = "0.0.2"
schema_version = 1
authors = ["Kyle Huggins <kyle@huggins.io>"]
description = "Basic EDI X12 language support."
repository = "https://github.com/hugginsio/zed-edi"

[grammars.x12]
repository = "https://github.com/hugginsio/tree-sitter-x12"
commit = "cfb81db868feff29befb6a58d50a06e9ce39e484"
